### ISSUE TITLE
participant level test data

### ISSUE THREAD

**Issue by fliem** [bids-apps/tracula#11]
Add precomputed participant level test data to circleci to run group level tests

**Comment by fliem** [comment]
I have created [new test data for ds114](https://github.com/BIDS-Apps/tracula/blob/master/circle.yml#L17): Freesurfer recons to test tracula participant level, and precomputed tracula participant level data to test tracula group level. There are 4 new zip files, 2 for cross-sectional and 2 for longitudinal data:

- [1](https://www.dropbox.com/s/li03ivxan6nlokd/ds114_test1_freesurfer.tar?dl=0)
- [2](https://www.dropbox.com/s/qf3t2gnfa1te9r5/ds114_test2_freesurfer.tar?dl=0) 
- [3](https://www.dropbox.com/s/aovt1ceybj614nk/ds114_test1_tracula_precomp.tar?dl=0) 
- [4](https://www.dropbox.com/s/1zyae2rqslyygdm/ds114_test2_tracula_precomp.tar?dl=0) 

@chrisfilo: Could you please upload them to osf and post the links. Thanks

**Comment by chrisgorgo** [comment]
On Fri, Jan 20, 2017 at 1:56 AM, Franz Liem <notifications@github.com>
wrote:

> I have created new test data for ds114
> <https://github.com/BIDS-Apps/tracula/blob/master/circle.yml#L17>:
> Freesurfer recons to test tracula participant level, and precomputed
> tracula participant level data to test tracula group level. There are 4 new
> zip files, 2 for cross-sectional and 2 for longitudinal data:
>
>    - 1
>    <https://www.dropbox.com/s/li03ivxan6nlokd/ds114_test1_freesurfer.tar?dl=0>
>
>
https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/5882adf3b83f6901f564da49

>
>    - 2
>    <https://www.dropbox.com/s/qf3t2gnfa1te9r5/ds114_test2_freesurfer.tar?dl=0>
>
>
https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/5882b0e3b83f6901fb64da18


>
>    - 3
>    <https://www.dropbox.com/s/aovt1ceybj614nk/ds114_test1_tracula_precomp.tar?dl=0>
>
>
https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/5882af28594d9001f447f03a


>
>    - 4
>    <https://www.dropbox.com/s/1zyae2rqslyygdm/ds114_test2_tracula_precomp.tar?dl=0>
>
>
https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/5882b3c3594d9001f047f031

**Comment by fliem** [comment]
Thanks
