### ISSUE TITLE
circleci cache

### ISSUE THREAD

**Issue by fliem** [bids-apps/tracula#15]
Hi @chrisfilo. Caching seems to be broken at the tracula circleci, for instance, [here](https://circleci.com/gh/BIDS-Apps/tracula/98) the docker build downloads everything. I think that it never has worked. Is there a setting that's not on for caching to work? Thanks

**Comment by chrisgorgo** [comment]
Hmm... Might be worth checking with CircleCI forums. Caching only worked with docker 1.9 in the past.
