### ISSUE TITLE
[feature request] - run recon_all if freesurfer directory not found

### ISSUE THREAD

**Issue by chrisgorgo** [bids-apps/tracula#20]
Right now if freesurfer data is not found tracula issues a warning and does not run anything (exiting with 0 which is a bit misleading). It would be good if it could also work as a "one stop shop" going directly from raw data and not depending on freesurfer. This would allow us to deploy it on OpenNeuro (without waiting for app chaining to be implemented) and would increase reproducibility.

**Comment by fliem** [comment]
Sounds good. As far as I remember, we cannot run docker from within docker, right?
