### ISSUE TITLE
Dockerfile fails because python is outdated and pandas does not install anymore

### ISSUE THREAD

**Issue by HaukeBartsch** [bids-apps/tracula#23]
Running the docker build I get an error that pandas could not be installed. This seems to be caused by python version 3.4 which is standard for ubuntu 14.04 which is used by the fsl base image. That version of python is not compatible anymore with pandas.

**Comment by fliem** [comment]
Thanks for reporting this. Are you interested in creating a PR with an update, for instance by updating the upstream images?
Thanks.
