### ISSUE TITLE
CI fails (command took > 2h)

### ISSUE THREAD

**Issue by fliem** [bids-apps/tracula#9]
Hi @chrisfilo.
The [build](https://circleci.com/gh/BIDS-Apps/tracula/11?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) [fails](https://circleci.com/api/v1.1/project/github/BIDS-Apps/tracula/11/output/13/0?file=true) while installing freesurfer (we need the trctrain directory, that's probably why it takes longer than with the freesurfer repo).
`command docker build -t bids/${CIRCLE_PROJECT_REPONAME,,} . took more than 120 minutes to run`
It seems 2h the circle hard limit per command.
Any experience with that? Thanks

**Comment by chrisgorgo** [comment]
Hmm, not sure what to recommend. I always had the impression that
https://github.com/BIDS-Apps/tracula/blob/master/Dockerfile#L6 still needs
to download all of FS, but some folders will be skipped in the extraction.
This would mean that skipping trctrain would save space, but not shorten
the execution time. Not quite sure what is going on.

For fmriprep building the container witt FS6 takes less than 15 minutes...
https://circleci.com/gh/chrisfilo/fmriprep/219?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by fliem** [comment]
circumvented by creating tracula_base image
